M48
; DRILL file {KiCad 7.0.7} date Sun Oct 22 12:38:50 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-22T12:38:50-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1063
%
G90
G05
T1
X2.7512Y-2.1756
X2.7512Y-2.4031
T2
X2.815Y-1.6919
X4.9203Y-2.6083
X5.4626Y-1.3376
T0
M30
